apiVersion: apps/v1
kind: Deployment
metadata:
  name: zpl
spec:
  selector:
    matchLabels:
      app: zpl
  template:
    metadata:
      labels:
        app: zpl
    spec:
      containers:
      - name: zpl
        image: apache/zeppelin:0.9.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zpl-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: zpl
