apiVersion: apps/v1
kind: Deployment
metadata:
  name: zepplein-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zpl
  template:
    metadata:
      labels:
        app: zpl
    spec:
      containers:
        - name: zeppelin
          image: apache/zeppelin:0.9.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory:
              cpu:
---
apiVersion: v1
kind: Service
metadata:
  name: zpl-svc
spec:
  selector:
     app: zpl
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
